/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "on-primary": "#ffffff",
        "success-pulse": "#22C55E",
        "primary-fixed": "#dbe1ff",
        "gold-light": "#FEDA75",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#b3c5ff",
        "inverse-on-surface": "#eff1f3",
        outline: "#757682",
        primary: "#00113a",
        "timer-warning": "#F97316",
        error: "#ba1a1a",
        "gold-dark": "#E5B630",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-fixed": "#00174a",
        "surface-tint": "#435b9f",
        secondary: "#755b00",
        "text-muted": "#525252",
        "on-surface": "#191c1e",
        tertiary: "#141414",
        "timer-urgent": "#EF4444",
        "on-tertiary-fixed-variant": "#474646",
        "outline-variant": "#c5c6d2",
        "on-tertiary-container": "#918f8e",
        "on-primary-container": "#758dd5",
        "border-subtle": "#E5E7EB",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444650",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed-variant": "#2a4386",
        surface: "#f7f9fb",
        "surface-container": "#eceef0",
        "primary-container": "#002366",
        "surface-dim": "#d8dadc",
        "navy-light": "#1A3C7A",
        "on-secondary-fixed-variant": "#594400",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#1c1b1b",
        "secondary-fixed-dim": "#efc137",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#241a00",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#292828",
        "secondary-fixed": "#ffdf92",
        "on-secondary-container": "#725800",
        "on-background": "#191c1e",
        "navy-dark": "#00153D",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#ffcf45",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "margin-desktop": "2.5rem",
        "touch-target": "2.75rem",
        "margin-mobile": "1rem",
        "section-gap": "5rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display-bid": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "data-tabular": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl-mobile": ["36px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-bid": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["60px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "data-tabular": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
